---

- hosts: all
  remote_user: root
  tasks:
    - name: install restic
      apt:
        name: restic
        state: present
    - name: copy restic password to file
      copy:
        content: "{{ vault_restic_password }}"
        dest: /root/.restic-password
        mode: 0600
    - name: Add AWS_ACCESS_KEY_ID cron env variable
      cron:
        env: true
        name: AWS_ACCESS_KEY_ID
        state: present
        value: "{{ vault_aws_access_key_id }}"
    - name: Add AWS_SECRET_ACCESS_KEY cron env variable
      cron:
        env: true
        name: AWS_SECRET_ACCESS_KEY
        state: present
        value: "{{ vault_aws_secret_access_key }}"
    - name: regular yunohost backup with cron
      cron:
        name: Create yunohost backup
        minute: 0
        hour: 3
        user: root
        state: absent
        job: yunohost backup create
    - name: remove older backups
      cron:
        name: remove older backups
        minute: 50
        hour: 3
        user: root
        state: absent
        job: yunohost backup list | tail -n +2 | head -n -3 | cut -c 4- | xargs -L1 --no-run-if-empty yunohost backup delete
    - name: regular uploading the backup to s3 with restic
      cron:
        name: "Upload yunohost backup to s3"
        minute: "0"
        hour: "4"
        user: root
        state: absent
        job: "restic backup /home/yunohost.backup/archives/ --repo s3:https://s3.fr-par.scw.cloud/telescoop-restic-yunohost --password-file /root/.restic-password"
    - name: restic - only keep last backup
      cron:
        name: "Only keep recent yunohost backups"
        minute: "0"
        hour: "5"
        user: root
        state: absent
        job: "restic forget --keep-last 3 --prune /home/yunohost.backup/archives/ --repo s3:https://s3.fr-par.scw.cloud/telescoop-restic-yunohost --password-file /root/.restic-password"
    - name: remove old n8n execution data
      cron:
        name: "remove old n8n execution entities"
        minute: "*/5"
        user: root
        state: present
        job: su postgres -c "psql -d n8n -c 'delete from execution_entity where \"id\" not in (SELECT \"id\" FROM execution_entity order by \"id\" desc limit 3000);'"
    - name: remove old n8n execution data
      cron:
        name: "remove old n8n execution data"
        minute: "*/5"
        user: root
        state: present
        job: su postgres -c "psql -d n8n -c 'delete from execution_data where \"executionId\" not in (SELECT \"id\" FROM execution_entity);'"
